### ISSUE TITLE
Can Vega apply displacement constraints to surface nodes and solve for the displacement at an internal point?

### ISSUE THREAD

**Issue by Jackie-zh** [starseeker/VegaFEM#2]
If so, which function should be used to implement this?

Thanks a lot!!

**Comment by starseeker** [comment]
Hi!  Apologies, but I'm afraid VegaFEM is long out of context for me, so I can't offer much help.  I suggest contacting the upstream developers:  https://viterbi-web.usc.edu/~jbarbic/vega/
